### ISSUE TITLE
ScriptDom.TSqlParser fails parsing valid expression

### ISSUE THREAD

**Issue by clement911** [microsoft/sqltoolsservice#868] opened 2019-09-23 07:41 UTC
I understand that Microsoft.SqlServer.TransactSql.ScriptDom.dll is not directly maintained here, but it seems to be the closest 'official' place to report bugs for this dll.
Is that right?
I really hope Microsoft opens sources Microsoft.SqlServer.TransactSql.ScriptDom but in the meantime I'll post the issue here and hope it can be reported internally to the relevant upstream team at Microsoft.

```
var parser = new TSql150Parser(true);
            string expr = @"
IIF
(
 (IIF(1 = 1, 1, NULL)) IS NULL,
 1,
 0
)";
            var res = parser.ParseExpression(new StringReader(expr), out var errors);
            bool isSuccess = errors.Count == 0;
```

Actual result: isSuccess is false
Expected result: isSuccess is true

**Comment by clement911** [comment] 2019-09-27 10:34
The following expression also fails to parse:

```
IIF
(
ABS(IIF(1=1, 1, 0)) > 1,
1,
0)
```

**Comment by clement911** [comment] 2019-09-27 12:42
Please vote here:
https://feedback.azure.com/forums/908035-sql-server/suggestions/38694355-microsoft-sqlserver-transactsql-scriptdom-tsqlpars

**Comment by arvindshmicrosoft** [comment] 2021-10-21 16:44
@dzsquared - FYI.

**Comment by clement911** [comment] 2022-03-07 07:45
Any update on this long standing bug? Very simple expressions cannot be parsed.

**Comment by Websure-Denzil** [comment] 2023-01-05 11:07
I know this is old, and I am very new to this - I expect @clement911 has already investigated - so I apologise in advance but I am curious.

There are obviously one or more errors being returned in the collection "errors".  Are the messages just blank, or is there something it _thinks_ it has found?

**Comment by clement911** [comment] 2023-01-10 01:43
@Websure-Denzil 

The errors contain a single error, but it is useless. I can't remember exactly but it is a generic error message such as 'Invalid syntax near (' or something similar.

This error is of course wrong. The syntax is valid.

**Comment by Websure-Denzil** [comment] 2023-01-10 09:00
> This error is of course wrong. The syntax is valid.

Indeed, that is frustrating.  It is a shame that such a simple, yet breaking error is left for so long.  I found this error when looking for such a utility for my own purposes.  If MS themselves cant be relied on for a reliable MS SQL parser, who can be?

**Comment by Charles-Gagnon** [comment] 2023-01-10 17:06
I'm going to close this one since it seems to be a duplicate of https://github.com/microsoft/DacFx/issues/183 and that's a better place for ScriptDom issues - and then I'll follow up with the owners to see if this is something they're going to be working on

**Closed by Charles-Gagnon** 2023-01-10 17:06 UTC

**Comment by Websure-Denzil** [comment] 2023-01-10 18:06
> I'm going to close this one since it seems to be a duplicate of [microsoft/DacFx#183](https://github.com/microsoft/DacFx/issues/183) and that's a better place for ScriptDom issues - and then I'll follow up with the owners to see if this is something they're going to be working on

but that one is closed too!
